version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    tty: true #Always running containe
